### ISSUE TITLE
github action to create apk package

### ISSUE THREAD

**Issue by Turiok** [cgutman/USBIPServerForAndroid#10]
Hi @cgutman  and thank you for your work here.

I think, it'll be good to create the APK with github action.
An official to playstore if it's possible. 
Otherwise maybe a not signed APK?

**Comment by CeruleanSky** [comment]
I forked it and added to .github/workflows a build.yml:

```
name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      #- name: Setup Android SDK
      #  uses: android-actions/setup-android@v3

      - name: Build SampleApplication
        run: |
            chmod +x ./gradlew
            ./gradlew --no-daemon build connectedCheck
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            ./app/build/outputs/apk/debug/app-debug.apk
          overwrite: true

```

Which worked for me.  Might want to branch it change master to your branches name in the above.
